### ISSUE TITLE
New version of Apama components and JsonUtil

### ISSUE THREAD

**Issue by tdalianis** [HEADS-project/ApamaComponents#18]
Hi,
The Apama Receiver sends out a message that is an Apama string and not a json string. In order for the response of the Receiver to be usable I updated the kevoreeNewsAssetCep project to include the JsonUtil class and tried to transform the message into json in the TestClient, but I get the following error

00:35 ERROR: Input port "/nodes[node0]/components[client]/provided[receiveMessage]" method threw an exception
com.apama.event.parser.ParserRuntimeException: EventParser.parse() : The EventType "Alarm" is not a known type in this parser.
        at com.apama.event.parser.EventParser.parse(EventParser.java:111)
        at atc.newsasset.test.TestClient.receiveMessage(TestClient.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.kevoree.library.java.wrapper.port.ProvidedPortImpl.send(ProvidedPortImpl.java:101)
        at org.kevoree.library.AsyncBroadcast$1.run(AsyncBroadcast.java:44)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I have tried with and without the apama namespaces but it doesn't make any difference. 
I will send the updated project and if you can please have a look.

**Comment by skorsky** [comment]
In my version of atc.newsasset.test.TestClient, I don't have a call the EventParser.
So there is no line which fits to
'at atc.newsasset.test.TestClient.receiveMessage(TestClient.java:78)'

@tdalianis: Can you share your version of the kevoreeNewsAssetCep project?
