### ISSUE TITLE
Unable to find kevoree.JavaNode

### ISSUE THREAD

**Issue by alliSoftwareAG** [HEADS-project/ApamaComponents#5]
Hi,

I have a problem, starting the apamaTest2 project.

I have a apama docker container running, but if I start mvn -e kev:run at the apamaTest2 project, I am getting the following error:

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building apamaTest 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for woodstox:wstx-asl:jar:3.2.4 is missing, no dependency information available
[WARNING] The POM for com.softwareag.apama:engine_client:jar:5.3 is missing, no dependency information available
[WARNING] The POM for com.softwareag.apama:utils:jar:5.3 is missing, no dependency information available
[INFO]
[INFO] --- org.kevoree.tools.mavenplugin:5.4.0-SNAPSHOT:run (default-cli) @ apamaTest2 ---
[INFO] Generating a Kevoree model by reflection...
[INFO] Model saved at target/classes/KEV-INF/kevlib.json
[INFO]
[INFO] Applying KevScript: src/main/kevs/main.kevs...
[INFO] On model: target/classes/KEV-INF/kevlib.json
00:00 INFO: Registry https://registry.kevoree.org
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.954s
[INFO] Finished at: Mon Nov 14 15:28:46 CET 2016
[INFO] Final Memory: 11M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.kevoree.tools:org.kevoree.tools.mavenplugin:5.4.0-SNAPSHOT:run (default-cli) on project apamaTest2: Something went wrong: Unable to find kevoree.JavaNode/LATEST/LATEST on the registry -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.kevoree.tools:org.kevoree.tools.mavenplugin:5.4.0-SNAPSHOT:run (default-cli) on project apamaTest2: Something went wrong
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: Something went wrong
        at org.kevoree.tools.mavenplugin.KevRunnerMojo.execute(KevRunnerMojo.java:162)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Something went wrong
        at org.kevoree.tools.mavenplugin.KevRunnerMojo.execute(KevRunnerMojo.java:156)
        ... 21 more
Caused by: java.lang.Exception: Unable to find kevoree.JavaNode/LATEST/LATEST on the registry
        at org.kevoree.kevscript.util.KevoreeRegistryResolver.processRegistryTypeDef(KevoreeRegistryResolver.java:69)
        at org.kevoree.kevscript.util.KevoreeRegistryResolver.resolve(KevoreeRegistryResolver.java:105)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:97)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:92)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:87)
        at org.kevoree.kevscript.KevScriptEngine.executeFromStream(KevScriptEngine.java:67)
        at org.kevoree.kevscript.KevScriptEngine.execute(KevScriptEngine.java:42)
        at org.kevoree.tools.mavenplugin.KevRunnerMojo.execute(KevRunnerMojo.java:135)
        ... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Can someone explain to me, what exactly I have to do to resolve that?

thank you so much :)

**Comment by skorsky** [comment]
@maxleiko , can issue #3 help here to renew the kevoree.JavaNode?

**Comment by maxleiko** [comment]
@skorsky nope

But [this one does](https://github.com/kevoree/kevoree-library/issues/20)

You need to use `https://kevoree.braindead.fr` for the moment as it is in-dev (and by default your $HOME/.kevoree/config.json is using https://kevoree.registry.org, which only works with the released Kevoree version and not the latest SNAPSHOT)
