### ISSUE TITLE
Could not find artifact

### ISSUE THREAD

**Issue by alliSoftwareAG** [HEADS-project/ApamaComponents#6]
Hi,

I have got a new issue, while I was trying to run the apamaTest2 project:

[alli@daevitesa01 apamaTest2]$ mvn kev:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building apamaTest 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for woodstox:wstx-asl:jar:3.2.4 is missing, no dependency information available
[WARNING] The POM for com.softwareag.apama:engine_client:jar:5.3 is missing, no dependency information available
[WARNING] The POM for com.softwareag.apama:utils:jar:5.3 is missing, no dependency information available
[INFO]
[INFO] --- org.kevoree.tools.mavenplugin:5.4.0-SNAPSHOT:run (default-cli) @ apamaTest2 ---
[INFO] Generating a Kevoree model by reflection...
[INFO] Model saved at target/classes/KEV-INF/kevlib.json
[INFO]
[INFO] Applying KevScript: src/main/kevs/main.kevs...
[INFO] On model: target/classes/KEV-INF/kevlib.json
00:00 INFO: Registry https://kevoree.braindead.fr
00:01 INFO: Found kevoree.JavaNode/1/LATEST in the registry
00:01 INFO: Found atc.TestApamaSubscriber2/14/LATEST in the registry
00:01 INFO: Found atc.TestApamaPublisher2/5/LATEST in the registry
00:01 INFO: Found atc.TestApamaTicker2/2/LATEST in the registry
00:02 INFO: Found kevoree.AsyncBroadcast/1/LATEST in the registry
00:02 INFO: Found kevoree.WSGroup/1/LATEST in the registry
[INFO]  => resulting model saved at target/classes/KEV-INF/ctxModel.json
[INFO]
[INFO] Starting Kevoree runtime using -Dnode.bootstrap=target/classes/KEV-INF/ctxModel.json
00:04 INFO: Log level= INFO
00:04 INFO: Registry https://kevoree.braindead.fr:443
00:04 INFO: Starting Kevoree using version: 5.4.0-SNAPSHOT
00:04 INFO: Platform node name: node0
00:04 INFO: Resolving ............. org.kevoree.library.java:org.kevoree.library.java.javaNode:5.4.0-SNAPSHOT
00:08 INFO: Resolved in 3328ms
00:08 INFO: Starting /nodes[node0]
00:08 INFO: Comparing models and planning adaptation
00:08 INFO: Launching adaptation of the system
00:08 INFO: Resolving ............. org.kevoree.project:apamaTest2:1.0.0-SNAPSHOT
00:10 ERROR: Unable to AddDeployUnit for /nodes[node0]/components[cmp2]
org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to collect/resolve dependency tree for a resolution due to: Could not find artifact org.kevoree.project:apamaTest2:jar:1.0.0-SNAPSHOT in central (https://repo.maven.apache.org/maven2), caused by: Could not find artifact org.kevoree.project:apamaTest2:jar:1.0.0-SNAPSHOT in central (https://repo.maven.apache.org/maven2)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.wrapException(MavenWorkingSessionImpl.java:492)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:231)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:71)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withoutTransitivity(MavenStrategyStageBaseImpl.java:58)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withoutTransitivity(MavenStrategyStageBaseImpl.java:40)
        at org.kevoree.bootstrap.kernel.KevoreeCLKernel.installDeployUnit(KevoreeCLKernel.java:153)
        at org.kevoree.library.java.command.AddDeployUnit.execute(AddDeployUnit.java:36)
        at org.kevoree.core.deploy.KevoreeSeqDeployPhase.execute(KevoreeSeqDeployPhase.java:27)
        at org.kevoree.core.deploy.PrimitiveCommandExecutionHelper.executeStep(PrimitiveCommandExecutionHelper.java:44)
        at org.kevoree.core.deploy.PrimitiveCommandExecutionHelper.execute(PrimitiveCommandExecutionHelper.java:19)
        at org.kevoree.core.KevoreeCoreBean.internal_update_model(KevoreeCoreBean.java:343)
        at org.kevoree.core.KevoreeCoreBean$UpdateModelRunnable.run(KevoreeCoreBean.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.kevoree.project:apamaTest2:jar:1.0.0-SNAPSHOT in central (https://repo.maven.apache.org/maven2)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.resolveDependencies(MavenRepositorySystem.java:121)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:228)
        ... 15 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kevoree.project:apamaTest2:jar:1.0.0-SNAPSHOT in central (https://repo.maven.apache.org/maven2)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 17 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.kevoree.project:apamaTest2:jar:1.0.0-SNAPSHOT in central (https://repo.maven.apache.org/maven2)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 19 more
00:10 ERROR: Error while executing primitive command AddDeployUnit atc/apamaTest2/1.0.0-SNAPSHOT/c9c5ddf58e9526e98102a8227675be81
00:10 WARN: JavaSENode is aborting last update...
00:10 INFO: End deploy result=false (2478ms)
00:10 WARN: JavaSENode update aborted in 2480 ms

The project is still running after that, but I am not sure, if it runs in a proper way (I do not think so).

Can somebody help me with this issue (once again)?

Thank you so much :)

**Comment by maxleiko** [comment]
Can you give the KevScript you used to start this runtime?

**Comment by alliSoftwareAG** [comment]
Martin gave to me this one at ~/apamaTest2/src/main/kevs/main.kevs: 

add node0 : JavaNode/LATEST/LATEST

add node0.cmp1 : atc.TestApamaSubscriber2/LATEST/LATEST 

add node0.cmp2 : atc.TestApamaPublisher2/LATEST/LATEST

add node0.cmp3 : atc.TestApamaTicker2/LATEST/LATEST

add chan665 : AsyncBroadcast/LATEST/LATEST

bind node0.cmp3.out chan665
bind node0.cmp2.in chan665

add sync : WSGroup/LATEST/LATEST
attach node0 sync

**Comment by barais** [comment]
you must run this script
https://github.com/HEADS-project/ApamaComponents/blob/master/installDependencies.sh

to add the dependencies in your local registry

**Comment by alliSoftwareAG** [comment]
Thank you very much, its running now.
